/*
 * generated by Xtext 2.13.0
 */
package com.project.foo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFooScopeProvider extends DelegatingScopeProvider {
}
