/*
 * generated by Xtext 2.13.0
 */
package com.project.foo.ui;

import com.google.inject.Injector;
import com.project.foo.ui.internal.FooActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FooExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(FooActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		FooActivator activator = FooActivator.getInstance();
		return activator != null ? activator.getInjector(FooActivator.COM_PROJECT_FOO_FOO) : null;
	}

}
