/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assembly</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.Assembly#getName <em>Name</em>}</li>
 *   <li>{@link com.project.foo.foo.Assembly#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link com.project.foo.foo.Assembly#getBindingsRequiered <em>Bindings Requiered</em>}</li>
 *   <li>{@link com.project.foo.foo.Assembly#getBindingsProvided <em>Bindings Provided</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getAssembly()
 * @model
 * @generated
 */
public interface Assembly extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.project.foo.foo.FooPackage#getAssembly_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.project.foo.foo.Assembly#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.ComponentInstance}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getAssembly_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<ComponentInstance> getAttributes();

  /**
   * Returns the value of the '<em><b>Bindings Requiered</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.BindingRequiered}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bindings Requiered</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bindings Requiered</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getAssembly_BindingsRequiered()
   * @model containment="true"
   * @generated
   */
  EList<BindingRequiered> getBindingsRequiered();

  /**
   * Returns the value of the '<em><b>Bindings Provided</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.BindingProvided}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bindings Provided</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bindings Provided</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getAssembly_BindingsProvided()
   * @model containment="true"
   * @generated
   */
  EList<BindingProvided> getBindingsProvided();

} // Assembly
