/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding Requiered</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.BindingRequiered#getName <em>Name</em>}</li>
 *   <li>{@link com.project.foo.foo.BindingRequiered#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getBindingRequiered()
 * @model
 * @generated
 */
public interface BindingRequiered extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(ComponentAttribute)
   * @see com.project.foo.foo.FooPackage#getBindingRequiered_Name()
   * @model
   * @generated
   */
  ComponentAttribute getName();

  /**
   * Sets the value of the '{@link com.project.foo.foo.BindingRequiered#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(ComponentAttribute value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(RequieredService)
   * @see com.project.foo.foo.FooPackage#getBindingRequiered_Type()
   * @model
   * @generated
   */
  RequieredService getType();

  /**
   * Sets the value of the '{@link com.project.foo.foo.BindingRequiered#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(RequieredService value);

} // BindingRequiered
