/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.Binding#getBindingRequired <em>Binding Required</em>}</li>
 *   <li>{@link com.project.foo.foo.Binding#getBindingProvided <em>Binding Provided</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getBinding()
 * @model
 * @generated
 */
public interface Binding extends EObject
{
  /**
   * Returns the value of the '<em><b>Binding Required</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Binding Required</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binding Required</em>' containment reference.
   * @see #setBindingRequired(BindingRequired)
   * @see com.project.foo.foo.FooPackage#getBinding_BindingRequired()
   * @model containment="true"
   * @generated
   */
  BindingRequired getBindingRequired();

  /**
   * Sets the value of the '{@link com.project.foo.foo.Binding#getBindingRequired <em>Binding Required</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binding Required</em>' containment reference.
   * @see #getBindingRequired()
   * @generated
   */
  void setBindingRequired(BindingRequired value);

  /**
   * Returns the value of the '<em><b>Binding Provided</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Binding Provided</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Binding Provided</em>' containment reference.
   * @see #setBindingProvided(BindingProvided)
   * @see com.project.foo.foo.FooPackage#getBinding_BindingProvided()
   * @model containment="true"
   * @generated
   */
  BindingProvided getBindingProvided();

  /**
   * Sets the value of the '{@link com.project.foo.foo.Binding#getBindingProvided <em>Binding Provided</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Binding Provided</em>' containment reference.
   * @see #getBindingProvided()
   * @generated
   */
  void setBindingProvided(BindingProvided value);

} // Binding
