/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding Provided</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.BindingProvided#getName <em>Name</em>}</li>
 *   <li>{@link com.project.foo.foo.BindingProvided#getService <em>Service</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getBindingProvided()
 * @model
 * @generated
 */
public interface BindingProvided extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(ComponentInstance)
   * @see com.project.foo.foo.FooPackage#getBindingProvided_Name()
   * @model
   * @generated
   */
  ComponentInstance getName();

  /**
   * Sets the value of the '{@link com.project.foo.foo.BindingProvided#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(ComponentInstance value);

  /**
   * Returns the value of the '<em><b>Service</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service</em>' reference.
   * @see #setService(PSignature)
   * @see com.project.foo.foo.FooPackage#getBindingProvided_Service()
   * @model
   * @generated
   */
  PSignature getService();

  /**
   * Sets the value of the '{@link com.project.foo.foo.BindingProvided#getService <em>Service</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service</em>' reference.
   * @see #getService()
   * @generated
   */
  void setService(PSignature value);

} // BindingProvided
