/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binding Requiered</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.BindingRequiered#getId <em>Id</em>}</li>
 *   <li>{@link com.project.foo.foo.BindingRequiered#getService <em>Service</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getBindingRequiered()
 * @model
 * @generated
 */
public interface BindingRequiered extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' reference.
   * @see #setId(ComponentInstance)
   * @see com.project.foo.foo.FooPackage#getBindingRequiered_Id()
   * @model
   * @generated
   */
  ComponentInstance getId();

  /**
   * Sets the value of the '{@link com.project.foo.foo.BindingRequiered#getId <em>Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' reference.
   * @see #getId()
   * @generated
   */
  void setId(ComponentInstance value);

  /**
   * Returns the value of the '<em><b>Service</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Service</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Service</em>' reference.
   * @see #setService(RequieredService)
   * @see com.project.foo.foo.FooPackage#getBindingRequiered_Service()
   * @model
   * @generated
   */
  RequieredService getService();

  /**
   * Sets the value of the '{@link com.project.foo.foo.BindingRequiered#getService <em>Service</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Service</em>' reference.
   * @see #getService()
   * @generated
   */
  void setService(RequieredService value);

} // BindingRequiered
