/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.ComponentAttribute#getName <em>Name</em>}</li>
 *   <li>{@link com.project.foo.foo.ComponentAttribute#getComposant <em>Composant</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getComponentAttribute()
 * @model
 * @generated
 */
public interface ComponentAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.project.foo.foo.FooPackage#getComponentAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.project.foo.foo.ComponentAttribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Composant</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Composant</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Composant</em>' reference.
   * @see #setComposant(Component)
   * @see com.project.foo.foo.FooPackage#getComponentAttribute_Composant()
   * @model
   * @generated
   */
  Component getComposant();

  /**
   * Sets the value of the '{@link com.project.foo.foo.ComponentAttribute#getComposant <em>Composant</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Composant</em>' reference.
   * @see #getComposant()
   * @generated
   */
  void setComposant(Component value);

} // ComponentAttribute
