/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.Model#getPackageName <em>Package Name</em>}</li>
 *   <li>{@link com.project.foo.foo.Model#getImports <em>Imports</em>}</li>
 *   <li>{@link com.project.foo.foo.Model#getComponent <em>Component</em>}</li>
 *   <li>{@link com.project.foo.foo.Model#getAssembly <em>Assembly</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Package Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Package Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Package Name</em>' attribute.
   * @see #setPackageName(String)
   * @see com.project.foo.foo.FooPackage#getModel_PackageName()
   * @model
   * @generated
   */
  String getPackageName();

  /**
   * Sets the value of the '{@link com.project.foo.foo.Model#getPackageName <em>Package Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Package Name</em>' attribute.
   * @see #getPackageName()
   * @generated
   */
  void setPackageName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.Import}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getModel_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Component</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.Component}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getModel_Component()
   * @model containment="true"
   * @generated
   */
  EList<Component> getComponent();

  /**
   * Returns the value of the '<em><b>Assembly</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.Assembly}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assembly</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assembly</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getModel_Assembly()
   * @model containment="true"
   * @generated
   */
  EList<Assembly> getAssembly();

} // Model
