/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.Model#getName <em>Name</em>}</li>
 *   <li>{@link com.project.foo.foo.Model#getImports <em>Imports</em>}</li>
 *   <li>{@link com.project.foo.foo.Model#getComponents <em>Components</em>}</li>
 *   <li>{@link com.project.foo.foo.Model#getAssembly <em>Assembly</em>}</li>
 *   <li>{@link com.project.foo.foo.Model#getRefiningList <em>Refining List</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.project.foo.foo.FooPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.project.foo.foo.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.Import}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Imports</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getModel_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Components</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.Component}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Components</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Components</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getModel_Components()
   * @model containment="true"
   * @generated
   */
  EList<Component> getComponents();

  /**
   * Returns the value of the '<em><b>Assembly</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.Assembly}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assembly</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assembly</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getModel_Assembly()
   * @model containment="true"
   * @generated
   */
  EList<Assembly> getAssembly();

  /**
   * Returns the value of the '<em><b>Refining List</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.Refine}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Refining List</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refining List</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getModel_RefiningList()
   * @model containment="true"
   * @generated
   */
  EList<Refine> getRefiningList();

} // Model
