/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>MProvided Service</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.MProvidedService#getSignature <em>Signature</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getMProvidedService()
 * @model
 * @generated
 */
public interface MProvidedService extends EObject
{
  /**
   * Returns the value of the '<em><b>Signature</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Signature</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signature</em>' containment reference.
   * @see #setSignature(PSignature)
   * @see com.project.foo.foo.FooPackage#getMProvidedService_Signature()
   * @model containment="true"
   * @generated
   */
  PSignature getSignature();

  /**
   * Sets the value of the '{@link com.project.foo.foo.MProvidedService#getSignature <em>Signature</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signature</em>' containment reference.
   * @see #getSignature()
   * @generated
   */
  void setSignature(PSignature value);

} // MProvidedService
