/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Provided</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.Provided#getProvidedServices <em>Provided Services</em>}</li>
 * </ul>
 *
 * @see com.project.foo.foo.FooPackage#getProvided()
 * @model
 * @generated
 */
public interface Provided extends EObject
{
  /**
   * Returns the value of the '<em><b>Provided Services</b></em>' containment reference list.
   * The list contents are of type {@link com.project.foo.foo.ProvidedService}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Provided Services</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Provided Services</em>' containment reference list.
   * @see com.project.foo.foo.FooPackage#getProvided_ProvidedServices()
   * @model containment="true"
   * @generated
   */
  EList<ProvidedService> getProvidedServices();

} // Provided
