/*
 * generated by Xtext 2.13.0
 */
package com.project.foo.serializer;

import com.google.inject.Inject;
import com.project.foo.services.FooGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class FooSyntacticSequencer extends AbstractSyntacticSequencer {

	protected FooGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Component___AssemblyKeyword_8_0_0_ColonKeyword_8_0_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (FooGrammarAccess) access;
		match_Component___AssemblyKeyword_8_0_0_ColonKeyword_8_0_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getComponentAccess().getAssemblyKeyword_8_0_0()), new TokenAlias(false, false, grammarAccess.getComponentAccess().getColonKeyword_8_0_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Component___AssemblyKeyword_8_0_0_ColonKeyword_8_0_1__q.equals(syntax))
				emit_Component___AssemblyKeyword_8_0_0_ColonKeyword_8_0_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('assembly' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     assemblies+=[Assembly|QualifiedName] (ambiguity) assemblies+=[Assembly|QualifiedName]
	 *     mProvServices+=MProvidedService (ambiguity) assemblies+=[Assembly|QualifiedName]
	 *     mReqServices+=MRequiredService (ambiguity) assemblies+=[Assembly|QualifiedName]
	 */
	protected void emit_Component___AssemblyKeyword_8_0_0_ColonKeyword_8_0_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
