/*
 * generated by Xtext 2.13.0
 */
package com.project.foo.ide

import com.google.inject.Guice
import com.project.foo.FooRuntimeModule
import com.project.foo.FooStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class FooIdeSetup extends FooStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new FooRuntimeModule, new FooIdeModule))
	}
	
}
