/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.foo.impl;

import com.project.foo.foo.Binding;
import com.project.foo.foo.BindingProvided;
import com.project.foo.foo.BindingRequired;
import com.project.foo.foo.FooPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Binding</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.project.foo.foo.impl.BindingImpl#getBindingRequired <em>Binding Required</em>}</li>
 *   <li>{@link com.project.foo.foo.impl.BindingImpl#getBindingProvided <em>Binding Provided</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BindingImpl extends ElementImpl implements Binding
{
  /**
   * The cached value of the '{@link #getBindingRequired() <em>Binding Required</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBindingRequired()
   * @generated
   * @ordered
   */
  protected BindingRequired bindingRequired;

  /**
   * The cached value of the '{@link #getBindingProvided() <em>Binding Provided</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBindingProvided()
   * @generated
   * @ordered
   */
  protected BindingProvided bindingProvided;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BindingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FooPackage.Literals.BINDING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BindingRequired getBindingRequired()
  {
    return bindingRequired;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBindingRequired(BindingRequired newBindingRequired, NotificationChain msgs)
  {
    BindingRequired oldBindingRequired = bindingRequired;
    bindingRequired = newBindingRequired;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FooPackage.BINDING__BINDING_REQUIRED, oldBindingRequired, newBindingRequired);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBindingRequired(BindingRequired newBindingRequired)
  {
    if (newBindingRequired != bindingRequired)
    {
      NotificationChain msgs = null;
      if (bindingRequired != null)
        msgs = ((InternalEObject)bindingRequired).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FooPackage.BINDING__BINDING_REQUIRED, null, msgs);
      if (newBindingRequired != null)
        msgs = ((InternalEObject)newBindingRequired).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FooPackage.BINDING__BINDING_REQUIRED, null, msgs);
      msgs = basicSetBindingRequired(newBindingRequired, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FooPackage.BINDING__BINDING_REQUIRED, newBindingRequired, newBindingRequired));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BindingProvided getBindingProvided()
  {
    return bindingProvided;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetBindingProvided(BindingProvided newBindingProvided, NotificationChain msgs)
  {
    BindingProvided oldBindingProvided = bindingProvided;
    bindingProvided = newBindingProvided;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, FooPackage.BINDING__BINDING_PROVIDED, oldBindingProvided, newBindingProvided);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBindingProvided(BindingProvided newBindingProvided)
  {
    if (newBindingProvided != bindingProvided)
    {
      NotificationChain msgs = null;
      if (bindingProvided != null)
        msgs = ((InternalEObject)bindingProvided).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - FooPackage.BINDING__BINDING_PROVIDED, null, msgs);
      if (newBindingProvided != null)
        msgs = ((InternalEObject)newBindingProvided).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - FooPackage.BINDING__BINDING_PROVIDED, null, msgs);
      msgs = basicSetBindingProvided(newBindingProvided, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FooPackage.BINDING__BINDING_PROVIDED, newBindingProvided, newBindingProvided));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FooPackage.BINDING__BINDING_REQUIRED:
        return basicSetBindingRequired(null, msgs);
      case FooPackage.BINDING__BINDING_PROVIDED:
        return basicSetBindingProvided(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FooPackage.BINDING__BINDING_REQUIRED:
        return getBindingRequired();
      case FooPackage.BINDING__BINDING_PROVIDED:
        return getBindingProvided();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FooPackage.BINDING__BINDING_REQUIRED:
        setBindingRequired((BindingRequired)newValue);
        return;
      case FooPackage.BINDING__BINDING_PROVIDED:
        setBindingProvided((BindingProvided)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FooPackage.BINDING__BINDING_REQUIRED:
        setBindingRequired((BindingRequired)null);
        return;
      case FooPackage.BINDING__BINDING_PROVIDED:
        setBindingProvided((BindingProvided)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FooPackage.BINDING__BINDING_REQUIRED:
        return bindingRequired != null;
      case FooPackage.BINDING__BINDING_PROVIDED:
        return bindingProvided != null;
    }
    return super.eIsSet(featureID);
  }

} //BindingImpl
