/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.ui.contentassist;

import com.project.foo.ui.contentassist.AbstractFooProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class FooProposalProvider extends AbstractFooProposalProvider {
}
