/**
 * generated by Xtext 2.13.0
 */
package com.project.foo;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import com.project.foo.AbstractFooRuntimeModule;
import com.project.foo.scoping.FooScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class FooRuntimeModule extends AbstractFooRuntimeModule {
  @Override
  public void configureIScopeProviderDelegate(final Binder binder) {
    binder.<IScopeProvider>bind(IScopeProvider.class).annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(
      FooScopeProvider.class);
  }
}
