/**
 * generated by Xtext 2.13.0
 */
package com.project.foo.ui;

import com.project.foo.ui.AbstractFooUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FooUiModule extends AbstractFooUiModule {
  public FooUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
